### ISSUE TITLE
results

### ISSUE THREAD

**Issue by HopefulWW** [BeyondHeaven/uec_code#1]
Hello， I would like to ask what are the three images ‘img1’, ‘fake_img’, ‘img2’ saved to the results folder?

**Comment by HopefulWW** [comment]
I'd also like to ask what I should do if I only want to save the exposure corrected image in the results.

**Comment by BeyondHeaven** [comment]
Hello,

1. The three images saved to the results folder are:
   - **img1**: The input image.
   - **fake_img**: The result of the UEC.
   - **img2**: The reference image (specified using `--ref_image_paths`).

2. If you only want to save the exposure corrected image in the results, you can set `self.visual_names = ['fake_img']` in the [uec_model.py](https://github.com/BeyondHeaven/uec_code/blob/main/models/uec_model.py#L20).
